TODO: Rerun with both organisms!

In [1]:
from pathlib import Path
import pandas as pd
import re
import sqlite3

In [2]:
conn = sqlite3.connect('../sqlite_backend.db')

In [3]:
#Alternative, for future reference
cursor = conn.cursor()
cursor.execute('SELECT TAXCODE, NAME FROM ORGANISM')
cursor.fetchall()

[(9606, 'Homo sapiens'), (10090, 'Mus musculus')]

Retrieve manually inputted data from database

In [4]:
organism_df = pd.read_sql_query('SELECT * FROM ORGANISM', conn)
organism_df

   TAXCODE          NAME
0     9606  Homo sapiens
1    10090  Mus musculus

In [5]:
taxcode = organism_df.loc[0]['TAXCODE']
taxcode

np.int64(9606)

In [6]:
protease_df = pd.read_sql_query('SELECT * FROM PROTEASE', conn)
protease_df

   PROTEASE_ID     NAME CLEAVAGE_RULE
0            1  Trypsin   ([KR])(?!P)

In [7]:
protease_id = protease_df.loc[0]['PROTEASE_ID']
protease_id

np.int64(1)

In [8]:
cleavage_rule = protease_df.loc[0]['CLEAVAGE_RULE']
cleavage_rule_compiled = re.compile(cleavage_rule)
cleavage_rule_compiled

re.compile(r'([KR])(?!P)', re.UNICODE)

In [9]:
modification_df = pd.read_sql_query('SELECT * FROM MODIFICATION', conn)
modification_df

   MODIFICATION_ID             NAME SYMBOL MODIFIABLE_RESIDUES
0                1  Phosphorylation   (ph)                 STY

In [10]:
modification_id = modification_df.loc[0]['MODIFICATION_ID']
modifiable_residues = modification_df.loc[0]['MODIFIABLE_RESIDUES']

Determine Fasta File using the taxcode

In [11]:
matching_files = list(Path('../resources/').glob(f'uniprot_proteome_w_isoforms_{taxcode}*.fasta'))
if len(matching_files) > 1:
    print(f'''More than one fasta files match! Ambiguous.
    The following files match: {[f.name for f in matching_files]} 
    ''')
else:
    fasta_path = matching_files[0]
    print(fasta_path)

..\resources\uniprot_proteome_w_isoforms_9606_20250829.fasta

In [12]:
#For debug
#fasta_path = Path('../resources/uniprot_fasta_stub.fasta')

In [8]:
def digest_sequence(sequence, cleavage_regex, n_missed_cleavages):
    sequences_wo_missed_cleavages = []
    previous_index = 0
    for match in re.finditer(cleavage_regex, sequence):
        sequences_wo_missed_cleavages.append({
            'seq': sequence[previous_index:match.start()+1],
            'start': previous_index+1,
            'end': match.start()+1
        })
        previous_index = match.start()+1
    #Add final stretch
    sequences_wo_missed_cleavages.append({
        'seq': sequence[previous_index:],
        'start': previous_index+1,
        'end': len(sequence)
    })
    sequences_w_missed_cleavages = []
    for i in range(len(sequences_wo_missed_cleavages)):
        for j in range(n_missed_cleavages+1):
            if i+j < len(sequences_wo_missed_cleavages):
                peptide_seq = "".join([entry['seq'] for entry in sequences_wo_missed_cleavages[i:i+j+1]])
                sequences_w_missed_cleavages.append({
                    'SEQUENCE':peptide_seq, 
                    'START_POSITION':sequences_wo_missed_cleavages[i]['start'] , 
                    'END_POSITION': sequences_wo_missed_cleavages[i+j]['end']})
    
    #Optionally cleave away the N-terminal methionine
    res = []
    for tryptic_peptide in sequences_w_missed_cleavages:
        res.append(tryptic_peptide)
        if tryptic_peptide['START_POSITION'] == 1 and tryptic_peptide['SEQUENCE'][0] == 'M':
            res.append({'SEQUENCE':tryptic_peptide['SEQUENCE'][1:] , 'START_POSITION':2, 'END_POSITION': tryptic_peptide['END_POSITION']})
    return res

In [14]:
def get_or_create_peptide_ids(peptides_of_protein, peptides, protein_to_peptides, current_peptide_id):
    for peptide in peptides_of_protein:
        if (existing_peptide_id:=peptides.get(peptide['SEQUENCE'])):
            peptide['PEPTIDE_ID'] = existing_peptide_id
        else:
            peptide['PEPTIDE_ID'] = current_peptide_id
            peptides[peptide['SEQUENCE']] = current_peptide_id
            current_peptide_id += 1
        peptide['PROTEIN_ID'] = current_protein_id
        #Remove sequence, it is not stored in the protein_to_peptides table
        peptide.pop('SEQUENCE')
        protein_to_peptides.append(peptide)
    return protein_to_peptides, peptides, current_peptide_id

In [15]:
isoform_regex = re.compile(r' Isoform of ([A-Z0-9]+),')
def get_canonical_protein_id(proteins, rest_string):
    isoform_match = re.search(isoform_regex, rest)
    if isoform_match:
        parent_protein = proteins.get(isoform_match.group(1))
        if not parent_protein:
            print(f'Canonical Isoform {isoform_match} not found!')
            return None
        else: 
            return parent_protein['PROTEIN_ID']
    else: 
        return None

In [16]:
gene_name_regex = re.compile(r'GN=([A-Z0-9]+)')
def get_gene_name(rest_string):
    gn_match = re.search(gene_name_regex, rest_string)
    if gn_match:
        return gn_match.group(1)
    else:
        return None

In [17]:
def extract_modified_sites(modified_sites, current_modified_site_id, protein_sequence, protein_id, uniprot_acc, modification_id, modifiable_residues):
    for index, aa in enumerate(protein_sequence):
        if aa in modifiable_residues:
            modified_sites.append({
                'MODIFIED_SITE_ID': current_modified_site_id,
                'PROTEIN_ID': protein_id,
                'MODIFICATION_ID': modification_id,
                'POSITION': index+1,
                'RESIDUE': aa,
                'SITE_IDENTIFIER': f'{uniprot_acc}_{aa}{index+1}'
            })
            current_modified_site_id +=1
    return modified_sites, current_modified_site_id

In [18]:
with open(fasta_path) as fasta_parsed:
    proteins = {}
    peptides = {}
    protein_to_peptides = []
    modified_sites = []
    current_protein_id = 1
    current_peptide_id = 1
    current_modified_site_id = 1
    sequence = ''
    while True:
        line=fasta_parsed.readline().strip()
        if not line or line[0] == '>':
            if sequence:
                #Digest using Trypsine cleavage rules and up to 4 missed cleavages
                peptides_of_protein = digest_sequence(sequence, cleavage_rule_compiled, 4)
                #Get or create peptide ids
                protein_to_peptides, peptides, current_peptide_id = get_or_create_peptide_ids(
                    peptides_of_protein, peptides, protein_to_peptides, current_peptide_id)
                #Extract modified sites
                modified_sites, current_modified_site_id = extract_modified_sites(modified_sites, current_modified_site_id, 
                                                                                  sequence, current_protein_id, 
                                                                                  uniprot, modification_id, modifiable_residues)
                #Check if the protein is a non-canonical isoform
                parent_protein_id = get_canonical_protein_id(proteins, rest)
                #Insert finished protein, maintain as a map with uniprots as keys - this way isoforms can easily find their parent
                proteins[uniprot] = {'PROTEIN_ID': current_protein_id, 'UNIPROT_ACC':uniprot,
                                     'GENE_NAME':gene_name, 'PARENT_PROTEIN_ID': parent_protein_id}
                #Prepare for the next protein
                if current_protein_id % 1000 == 0:
                    print(f'Processed {current_protein_id} proteins')
                current_protein_id += 1
                sequence = ''
            if line:
                db, uniprot, rest = line[1:].split('|')
                gene_name = get_gene_name(rest)
            else:
                break
        else:
            sequence += line

Processed 100 proteins
Processed 200 proteins
Processed 300 proteins
Processed 400 proteins
Processed 500 proteins
Processed 600 proteins
Processed 700 proteins
Processed 800 proteins
Processed 900 proteins
Processed 1000 proteins
Processed 1100 proteins
Processed 1200 proteins
Processed 1300 proteins
Processed 1400 proteins
Processed 1500 proteins
Processed 1600 proteins
Processed 1700 proteins
Processed 1800 proteins
Processed 1900 proteins
Processed 2000 proteins
Processed 2100 proteins
Processed 2200 proteins
Processed 2300 proteins
Processed 2400 proteins
Processed 2500 proteins
Processed 2600 proteins
Processed 2700 proteins
Processed 2800 proteins
Processed 2900 proteins
Processed 3000 proteins
Processed 3100 proteins
Processed 3200 proteins
Processed 3300 proteins
Processed 3400 proteins
Processed 3500 proteins
Processed 3600 proteins
Processed 3700 proteins
Processed 3800 proteins
Processed 3900 proteins
Processed 4000 proteins
Processed 4100 proteins
Processed 4200 proteins
Processed 4300 proteins
Processed 4400 proteins
Processed 4500 proteins
Processed 4600 proteins
Processed 4700 proteins
Processed 4800 proteins
Processed 4900 proteins
Processed 5000 proteins
Processed 5100 proteins
Processed 5200 proteins
Processed 5300 proteins
Processed 5400 proteins
Processed 5500 proteins
Processed 5600 proteins
Processed 5700 proteins
Processed 5800 proteins
Processed 5900 proteins
Processed 6000 proteins
Processed 6100 proteins
Processed 6200 proteins
Processed 6300 proteins
Processed 6400 proteins
Processed 6500 proteins
Processed 6600 proteins
Processed 6700 proteins
Processed 6800 proteins
Processed 6900 proteins
Processed 7000 proteins
Processed 7100 proteins
Processed 7200 proteins
Processed 7300 proteins
Processed 7400 proteins
Processed 7500 proteins
Processed 7600 proteins
Processed 7700 proteins
Processed 7800 proteins
Processed 7900 proteins
Processed 8000 proteins
Processed 8100 proteins
Processed 8200 proteins
Processed 8300 proteins
Processed 8400 proteins
Processed 8500 proteins
Processed 8600 proteins
Processed 8700 proteins
Processed 8800 proteins
Processed 8900 proteins
Processed 9000 proteins
Processed 9100 proteins
Processed 9200 proteins
Processed 9300 proteins
Processed 9400 proteins
Processed 9500 proteins
Processed 9600 proteins
Processed 9700 proteins
Processed 9800 proteins
Processed 9900 proteins
Processed 10000 proteins
Processed 10100 proteins
Processed 10200 proteins
Processed 10300 proteins
Processed 10400 proteins
Processed 10500 proteins
Processed 10600 proteins
Processed 10700 proteins
Processed 10800 proteins
Processed 10900 proteins
Processed 11000 proteins
Processed 11100 proteins
Processed 11200 proteins
Processed 11300 proteins
Processed 11400 proteins
Processed 11500 proteins
Processed 11600 proteins
Processed 11700 proteins
Processed 11800 proteins
Processed 11900 proteins
Processed 12000 proteins
Processed 12100 proteins
Processed 12200 proteins
Processed 12300 proteins
Processed 12400 proteins
Processed 12500 proteins
Processed 12600 proteins
Processed 12700 proteins
Processed 12800 proteins
Processed 12900 proteins
Processed 13000 proteins
Processed 13100 proteins
Processed 13200 proteins
Processed 13300 proteins
Processed 13400 proteins
Processed 13500 proteins
Processed 13600 proteins
Processed 13700 proteins
Processed 13800 proteins
Processed 13900 proteins
Processed 14000 proteins
Processed 14100 proteins
Processed 14200 proteins
Processed 14300 proteins
Processed 14400 proteins
Processed 14500 proteins
Processed 14600 proteins
Processed 14700 proteins
Processed 14800 proteins
Processed 14900 proteins
Processed 15000 proteins
Processed 15100 proteins
Processed 15200 proteins
Processed 15300 proteins
Processed 15400 proteins
Processed 15500 proteins
Processed 15600 proteins
Processed 15700 proteins
Processed 15800 proteins
Processed 15900 proteins
Processed 16000 proteins
Processed 16100 proteins
Processed 16200 proteins
Processed 16300 proteins
Processed 16400 proteins
Processed 16500 proteins
Processed 16600 proteins
Processed 16700 proteins
Processed 16800 proteins
Processed 16900 proteins
Processed 17000 proteins
Processed 17100 proteins
Processed 17200 proteins
Processed 17300 proteins
Processed 17400 proteins
Processed 17500 proteins
Processed 17600 proteins
Processed 17700 proteins
Processed 17800 proteins
Processed 17900 proteins
Processed 18000 proteins
Processed 18100 proteins
Processed 18200 proteins
Processed 18300 proteins
Processed 18400 proteins
Processed 18500 proteins
Processed 18600 proteins
Processed 18700 proteins
Processed 18800 proteins
Processed 18900 proteins
Processed 19000 proteins
Processed 19100 proteins
Processed 19200 proteins
Processed 19300 proteins
Processed 19400 proteins
Processed 19500 proteins
Processed 19600 proteins
Processed 19700 proteins
Processed 19800 proteins
Processed 19900 proteins
Processed 20000 proteins
Processed 20100 proteins
Processed 20200 proteins
Processed 20300 proteins
Processed 20400 proteins
Processed 20500 proteins
Processed 20600 proteins
Processed 20700 proteins
Processed 20800 proteins
Processed 20900 proteins
Processed 21000 proteins
Processed 21100 proteins
Processed 21200 proteins
Processed 21300 proteins
Processed 21400 proteins
Processed 21500 proteins
Processed 21600 proteins
Processed 21700 proteins
Processed 21800 proteins
Processed 21900 proteins
Processed 22000 proteins
Processed 22100 proteins
Processed 22200 proteins
Processed 22300 proteins
Processed 22400 proteins
Processed 22500 proteins
Processed 22600 proteins
Processed 22700 proteins
Processed 22800 proteins
Processed 22900 proteins
Processed 23000 proteins
Processed 23100 proteins
Processed 23200 proteins
Processed 23300 proteins
Processed 23400 proteins
Processed 23500 proteins
Processed 23600 proteins
Processed 23700 proteins
Processed 23800 proteins
Processed 23900 proteins
Processed 24000 proteins
Processed 24100 proteins
Processed 24200 proteins
Processed 24300 proteins
Processed 24400 proteins
Processed 24500 proteins
Processed 24600 proteins
Processed 24700 proteins
Processed 24800 proteins
Processed 24900 proteins
Processed 25000 proteins
Processed 25100 proteins
Processed 25200 proteins
Processed 25300 proteins
Processed 25400 proteins
Processed 25500 proteins
Processed 25600 proteins
Processed 25700 proteins
Processed 25800 proteins
Processed 25900 proteins
Processed 26000 proteins
Processed 26100 proteins
Processed 26200 proteins
Processed 26300 proteins
Processed 26400 proteins
Processed 26500 proteins
Processed 26600 proteins
Processed 26700 proteins
Processed 26800 proteins
Processed 26900 proteins
Processed 27000 proteins
Processed 27100 proteins
Processed 27200 proteins
Processed 27300 proteins
Processed 27400 proteins
Processed 27500 proteins
Processed 27600 proteins
Processed 27700 proteins
Processed 27800 proteins
Processed 27900 proteins
Processed 28000 proteins
Processed 28100 proteins
Processed 28200 proteins
Processed 28300 proteins
Processed 28400 proteins
Processed 28500 proteins
Processed 28600 proteins
Processed 28700 proteins
Processed 28800 proteins
Processed 28900 proteins
Processed 29000 proteins
Processed 29100 proteins
Processed 29200 proteins
Processed 29300 proteins
Processed 29400 proteins
Processed 29500 proteins
Processed 29600 proteins
Processed 29700 proteins
Processed 29800 proteins
Processed 29900 proteins
Processed 30000 proteins
Processed 30100 proteins
Processed 30200 proteins
Processed 30300 proteins
Processed 30400 proteins
Processed 30500 proteins
Processed 30600 proteins
Processed 30700 proteins
Processed 30800 proteins
Processed 30900 proteins
Processed 31000 proteins
Processed 31100 proteins
Processed 31200 proteins
Processed 31300 proteins
Processed 31400 proteins
Processed 31500 proteins
Processed 31600 proteins
Processed 31700 proteins
Processed 31800 proteins
Processed 31900 proteins
Processed 32000 proteins
Processed 32100 proteins
Processed 32200 proteins
Processed 32300 proteins
Processed 32400 proteins
Processed 32500 proteins
Processed 32600 proteins
Processed 32700 proteins
Processed 32800 proteins
Processed 32900 proteins
Processed 33000 proteins
Processed 33100 proteins
Processed 33200 proteins
Processed 33300 proteins
Processed 33400 proteins
Processed 33500 proteins
Processed 33600 proteins
Processed 33700 proteins
Processed 33800 proteins
Processed 33900 proteins
Processed 34000 proteins
Processed 34100 proteins
Processed 34200 proteins
Processed 34300 proteins
Processed 34400 proteins
Processed 34500 proteins
Processed 34600 proteins
Processed 34700 proteins
Processed 34800 proteins
Processed 34900 proteins
Processed 35000 proteins
Processed 35100 proteins
Processed 35200 proteins
Processed 35300 proteins
Processed 35400 proteins
Processed 35500 proteins
Processed 35600 proteins
Processed 35700 proteins
Processed 35800 proteins
Processed 35900 proteins
Processed 36000 proteins
Processed 36100 proteins
Processed 36200 proteins
Processed 36300 proteins
Processed 36400 proteins
Processed 36500 proteins
Processed 36600 proteins
Processed 36700 proteins
Processed 36800 proteins
Processed 36900 proteins
Processed 37000 proteins
Processed 37100 proteins
Processed 37200 proteins
Processed 37300 proteins
Processed 37400 proteins
Processed 37500 proteins
Processed 37600 proteins
Processed 37700 proteins
Processed 37800 proteins
Processed 37900 proteins
Processed 38000 proteins
Processed 38100 proteins
Processed 38200 proteins
Processed 38300 proteins
Processed 38400 proteins
Processed 38500 proteins
Processed 38600 proteins
Processed 38700 proteins
Processed 38800 proteins
Processed 38900 proteins
Processed 39000 proteins
Processed 39100 proteins
Processed 39200 proteins
Processed 39300 proteins
Processed 39400 proteins
Processed 39500 proteins
Processed 39600 proteins
Processed 39700 proteins
Processed 39800 proteins
Processed 39900 proteins
Processed 40000 proteins
Processed 40100 proteins
Processed 40200 proteins
Processed 40300 proteins
Processed 40400 proteins
Processed 40500 proteins
Processed 40600 proteins
Processed 40700 proteins
Processed 40800 proteins
Processed 40900 proteins
Processed 41000 proteins
Processed 41100 proteins
Processed 41200 proteins
Processed 41300 proteins
Processed 41400 proteins
Processed 41500 proteins
Processed 41600 proteins
Processed 41700 proteins
Processed 41800 proteins
Processed 41900 proteins
Processed 42000 proteins
Processed 42100 proteins
Processed 42200 proteins
Processed 42300 proteins
Processed 42400 proteins
Processed 42500 proteins
Processed 42600 proteins
Processed 42700 proteins
Processed 42800 proteins
Processed 42900 proteins
Processed 43000 proteins
Processed 43100 proteins
Processed 43200 proteins
Processed 43300 proteins
Processed 43400 proteins
Processed 43500 proteins
Processed 43600 proteins
Processed 43700 proteins
Processed 43800 proteins
Processed 43900 proteins
Processed 44000 proteins
Processed 44100 proteins
Processed 44200 proteins
Processed 44300 proteins
Processed 44400 proteins
Processed 44500 proteins
Processed 44600 proteins
Processed 44700 proteins
Processed 44800 proteins
Processed 44900 proteins
Processed 45000 proteins
Processed 45100 proteins
Processed 45200 proteins
Processed 45300 proteins
Processed 45400 proteins
Processed 45500 proteins
Processed 45600 proteins
Processed 45700 proteins
Processed 45800 proteins
Processed 45900 proteins
Processed 46000 proteins
Processed 46100 proteins
Processed 46200 proteins
Processed 46300 proteins
Processed 46400 proteins
Processed 46500 proteins
Processed 46600 proteins
Processed 46700 proteins
Processed 46800 proteins
Processed 46900 proteins
Processed 47000 proteins
Processed 47100 proteins
Processed 47200 proteins
Processed 47300 proteins
Processed 47400 proteins
Processed 47500 proteins
Processed 47600 proteins
Processed 47700 proteins
Processed 47800 proteins
Processed 47900 proteins
Processed 48000 proteins
Processed 48100 proteins
Processed 48200 proteins
Processed 48300 proteins
Processed 48400 proteins
Processed 48500 proteins
Processed 48600 proteins
Processed 48700 proteins
Processed 48800 proteins
Processed 48900 proteins
Processed 49000 proteins
Processed 49100 proteins
Processed 49200 proteins
Processed 49300 proteins
Processed 49400 proteins
Processed 49500 proteins
Processed 49600 proteins
Processed 49700 proteins
Processed 49800 proteins
Processed 49900 proteins
Processed 50000 proteins
Processed 50100 proteins
Processed 50200 proteins
Processed 50300 proteins
Processed 50400 proteins
Processed 50500 proteins
Processed 50600 proteins
Processed 50700 proteins
Processed 50800 proteins
Processed 50900 proteins
Processed 51000 proteins
Processed 51100 proteins
Processed 51200 proteins
Processed 51300 proteins
Processed 51400 proteins
Processed 51500 proteins
Processed 51600 proteins
Processed 51700 proteins
Processed 51800 proteins
Processed 51900 proteins
Processed 52000 proteins
Processed 52100 proteins
Processed 52200 proteins
Processed 52300 proteins
Processed 52400 proteins
Processed 52500 proteins
Processed 52600 proteins
Processed 52700 proteins
Processed 52800 proteins
Processed 52900 proteins
Processed 53000 proteins
Processed 53100 proteins
Processed 53200 proteins
Processed 53300 proteins
Processed 53400 proteins
Processed 53500 proteins
Processed 53600 proteins
Processed 53700 proteins
Processed 53800 proteins
Processed 53900 proteins
Processed 54000 proteins
Processed 54100 proteins
Processed 54200 proteins
Processed 54300 proteins
Processed 54400 proteins
Processed 54500 proteins
Processed 54600 proteins
Processed 54700 proteins
Processed 54800 proteins
Processed 54900 proteins
Processed 55000 proteins
Processed 55100 proteins
Processed 55200 proteins
Processed 55300 proteins
Processed 55400 proteins
Processed 55500 proteins
Processed 55600 proteins
Processed 55700 proteins
Processed 55800 proteins
Processed 55900 proteins
Processed 56000 proteins
Processed 56100 proteins
Processed 56200 proteins
Processed 56300 proteins
Processed 56400 proteins
Processed 56500 proteins
Processed 56600 proteins
Processed 56700 proteins
Processed 56800 proteins
Processed 56900 proteins
Processed 57000 proteins
Processed 57100 proteins
Processed 57200 proteins
Processed 57300 proteins
Processed 57400 proteins
Processed 57500 proteins
Processed 57600 proteins
Processed 57700 proteins
Processed 57800 proteins
Processed 57900 proteins
Processed 58000 proteins
Processed 58100 proteins
Processed 58200 proteins
Processed 58300 proteins
Processed 58400 proteins
Processed 58500 proteins
Processed 58600 proteins
Processed 58700 proteins
Processed 58800 proteins
Processed 58900 proteins
Processed 59000 proteins
Processed 59100 proteins
Processed 59200 proteins
Processed 59300 proteins
Processed 59400 proteins
Processed 59500 proteins
Processed 59600 proteins
Processed 59700 proteins
Processed 59800 proteins
Processed 59900 proteins
Processed 60000 proteins
Processed 60100 proteins
Processed 60200 proteins
Processed 60300 proteins
Processed 60400 proteins
Processed 60500 proteins
Processed 60600 proteins
Processed 60700 proteins
Processed 60800 proteins
Processed 60900 proteins
Processed 61000 proteins
Processed 61100 proteins
Processed 61200 proteins
Processed 61300 proteins
Processed 61400 proteins
Processed 61500 proteins
Processed 61600 proteins
Processed 61700 proteins
Processed 61800 proteins
Processed 61900 proteins
Processed 62000 proteins
Processed 62100 proteins
Processed 62200 proteins
Processed 62300 proteins
Processed 62400 proteins
Processed 62500 proteins
Processed 62600 proteins
Processed 62700 proteins
Processed 62800 proteins
Processed 62900 proteins
Processed 63000 proteins
Processed 63100 proteins
Processed 63200 proteins
Processed 63300 proteins
Processed 63400 proteins
Processed 63500 proteins
Processed 63600 proteins
Processed 63700 proteins
Processed 63800 proteins
Processed 63900 proteins
Processed 64000 proteins
Processed 64100 proteins
Processed 64200 proteins
Processed 64300 proteins
Processed 64400 proteins
Processed 64500 proteins
Processed 64600 proteins
Processed 64700 proteins
Processed 64800 proteins
Processed 64900 proteins
Processed 65000 proteins
Processed 65100 proteins
Processed 65200 proteins
Processed 65300 proteins
Processed 65400 proteins
Processed 65500 proteins
Processed 65600 proteins
Processed 65700 proteins
Processed 65800 proteins
Processed 65900 proteins
Processed 66000 proteins
Processed 66100 proteins
Processed 66200 proteins
Processed 66300 proteins
Processed 66400 proteins
Processed 66500 proteins
Processed 66600 proteins
Processed 66700 proteins
Processed 66800 proteins
Processed 66900 proteins
Processed 67000 proteins
Processed 67100 proteins
Processed 67200 proteins
Processed 67300 proteins
Processed 67400 proteins
Processed 67500 proteins
Processed 67600 proteins
Processed 67700 proteins
Processed 67800 proteins
Processed 67900 proteins
Processed 68000 proteins
Processed 68100 proteins
Processed 68200 proteins
Processed 68300 proteins
Processed 68400 proteins
Processed 68500 proteins
Processed 68600 proteins
Processed 68700 proteins
Processed 68800 proteins
Processed 68900 proteins
Processed 69000 proteins
Processed 69100 proteins
Processed 69200 proteins
Processed 69300 proteins
Processed 69400 proteins
Processed 69500 proteins
Processed 69600 proteins
Processed 69700 proteins
Processed 69800 proteins
Processed 69900 proteins
Processed 70000 proteins
Processed 70100 proteins
Processed 70200 proteins
Processed 70300 proteins
Processed 70400 proteins
Processed 70500 proteins
Processed 70600 proteins
Processed 70700 proteins
Processed 70800 proteins
Processed 70900 proteins
Processed 71000 proteins
Processed 71100 proteins
Processed 71200 proteins
Processed 71300 proteins
Processed 71400 proteins
Processed 71500 proteins
Processed 71600 proteins
Processed 71700 proteins
Processed 71800 proteins
Processed 71900 proteins
Processed 72000 proteins
Processed 72100 proteins
Processed 72200 proteins
Processed 72300 proteins
Processed 72400 proteins
Processed 72500 proteins
Processed 72600 proteins
Processed 72700 proteins
Processed 72800 proteins
Processed 72900 proteins
Processed 73000 proteins
Processed 73100 proteins
Processed 73200 proteins
Processed 73300 proteins
Processed 73400 proteins
Processed 73500 proteins
Processed 73600 proteins
Processed 73700 proteins
Processed 73800 proteins
Processed 73900 proteins
Processed 74000 proteins
Processed 74100 proteins
Processed 74200 proteins
Processed 74300 proteins
Processed 74400 proteins
Processed 74500 proteins
Processed 74600 proteins
Processed 74700 proteins
Processed 74800 proteins
Processed 74900 proteins
Processed 75000 proteins
Processed 75100 proteins
Processed 75200 proteins
Processed 75300 proteins
Processed 75400 proteins
Processed 75500 proteins
Processed 75600 proteins
Processed 75700 proteins
Processed 75800 proteins
Processed 75900 proteins
Processed 76000 proteins
Processed 76100 proteins
Processed 76200 proteins
Processed 76300 proteins
Processed 76400 proteins
Processed 76500 proteins
Processed 76600 proteins
Processed 76700 proteins
Processed 76800 proteins
Processed 76900 proteins
Processed 77000 proteins
Processed 77100 proteins
Processed 77200 proteins
Processed 77300 proteins
Processed 77400 proteins
Processed 77500 proteins
Processed 77600 proteins
Processed 77700 proteins
Processed 77800 proteins
Processed 77900 proteins
Processed 78000 proteins
Processed 78100 proteins
Processed 78200 proteins
Processed 78300 proteins
Processed 78400 proteins
Processed 78500 proteins
Processed 78600 proteins
Processed 78700 proteins
Processed 78800 proteins
Processed 78900 proteins
Processed 79000 proteins
Processed 79100 proteins
Processed 79200 proteins
Processed 79300 proteins
Processed 79400 proteins
Processed 79500 proteins
Processed 79600 proteins
Processed 79700 proteins
Processed 79800 proteins
Processed 79900 proteins
Processed 80000 proteins
Processed 80100 proteins
Processed 80200 proteins
Processed 80300 proteins
Processed 80400 proteins

In [19]:
proteins_df = pd.DataFrame(proteins.values())
proteins_df['PARENT_PROTEIN_ID'] = proteins_df['PARENT_PROTEIN_ID'].astype('Int64')
proteins_df['TAXCODE'] = taxcode
proteins_df

        PROTEIN_ID UNIPROT_ACC GENE_NAME  PARENT_PROTEIN_ID  TAXCODE
0                1  A0A087X0M5    TRBV18               <NA>     9606
1                2      A6NEH6   TMEM247               <NA>     9606
2                3      A6NIH7   UNC119B               <NA>     9606
3                4      A6NJR5      None               <NA>     9606
4                5      A6NKF7   TMEM278               <NA>     9606
...            ...         ...       ...                ...      ...
105714      105715  A0A0D9SG52      None               <NA>     9606
105715      105716  A0A1W2PRQ8      None               <NA>     9606
105716      105717      C9J4A7      None               <NA>     9606
105717      105718      G3V3Y1      None               <NA>     9606
105718      105719      H0Y8G0      None               <NA>     9606

[105719 rows x 5 columns]

In [24]:
proteins_df.to_sql('PROTEIN', conn, if_exists='append', index=False)

105719

In [20]:
peptides_df = pd.DataFrame(peptides.items(), columns=['SEQUENCE','PEPTIDE_ID'])
peptides_df

                                   SEQUENCE  PEPTIDE_ID
0                                      MDTR           1
1              MDTRLLCCAVICLLGAGLSNAGVMQNPR           2
2          MDTRLLCCAVICLLGAGLSNAGVMQNPRHLVR           3
3         MDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRR           4
4        MDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRR           5
...                                     ...         ...
6215931                              XGSWYK     6215932
6215932                           XGSWYKHVK     6215933
6215933                      XGSWYKHVKSWWEK     6215934
6215934                    XGSWYKHVKSWWEKGK     6215935
6215935                 XGSWYKHVKSWWEKGKSPR     6215936

[6215936 rows x 2 columns]

In [25]:
peptides_df.to_sql('PEPTIDE', conn, if_exists='append', index=False)

6215936

In [21]:
protein_to_peptides_df = pd.DataFrame(protein_to_peptides)
protein_to_peptides_df['PROTEASE_ID'] = protease_id
protein_to_peptides_df

          START_POSITION  END_POSITION  PEPTIDE_ID  PROTEIN_ID  PROTEASE_ID
0                      1             4           1           1            1
1                      1            28           2           1            1
2                      1            32           3           1            1
3                      1            33           4           1            1
4                      1            34           5           1            1
...                  ...           ...         ...         ...          ...
23322808             118           124      525308      105719            1
23322809             118           127      525309      105719            1
23322810             123           124         759      105719            1
23322811             123           127      525310      105719            1
23322812             125           127      525311      105719            1

[23322813 rows x 5 columns]

In [26]:
protein_to_peptides_df.to_sql('PROTEIN_TO_PEPTIDE', conn, if_exists='append', index=False)

23322813

In [22]:
modified_sites_df = pd.DataFrame(modified_sites)
modified_sites_df

,MODIFIED_SITE_ID,PROTEIN_ID,MODIFICATION_ID,POSITION,RESIDUE,SITE_IDENTIFIER
0,1,1,1,3,T,A0A087X0M5_T3
1,2,1,1,19,S,A0A087X0M5_S19
2,3,1,1,43,S,A0A087X0M5_S43
3,4,1,1,49,S,A0A087X0M5_S49
4,5,1,1,52,Y,A0A087X0M5_Y52
...,...,...,...,...,...,...
7316638,7316639,105719,1,101,T,H0Y8G0_T101
7316639,7316640,105719,1,112,Y,H0Y8G0_Y112
7316640,7316641,105719,1,119,S,H0Y8G0_S119
7316641,7316642,105719,1,120,T,H0Y8G0_T120
7316642,7316643,105719,1,125,T,H0Y8G0_T125

In [27]:
modified_sites_df.to_sql('MODIFIED_SITE', conn, if_exists='append', index=False)

7316643